// <auto-generated />
using System;
using Garage2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage2._0.Migrations
{
    [DbContext(typeof(Garage2_0Context))]
    [Migration("20241030151819_SeededSomeVehicles")]
    partial class SeededSomeVehicles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garage2._0.Models.Entites.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckoutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("RegisterNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "BMW",
                            CheckoutTime = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Black",
                            Model = "X6",
                            NumberOfWheels = 4,
                            RegisterNumber = "RGC 234",
                            VehicleType = "Desiel"
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "VOLVO",
                            CheckoutTime = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "white",
                            Model = "V40",
                            NumberOfWheels = 4,
                            RegisterNumber = "INT 765",
                            VehicleType = "Bensin"
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "AUDI",
                            CheckoutTime = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "WHITE",
                            Model = "A6",
                            NumberOfWheels = 4,
                            RegisterNumber = "KMV 456",
                            VehicleType = "EL"
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "VOLVO",
                            CheckoutTime = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Black",
                            Model = "GX",
                            NumberOfWheels = 4,
                            RegisterNumber = "ZDG 980",
                            VehicleType = "Desiel"
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "SAAB",
                            CheckoutTime = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Black",
                            Model = "A5",
                            NumberOfWheels = 4,
                            RegisterNumber = "LKW 285",
                            VehicleType = "Desiel"
                        },
                        new
                        {
                            Id = 6,
                            ArrivalTime = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "KIA",
                            CheckoutTime = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "RED",
                            Model = "BX",
                            NumberOfWheels = 4,
                            RegisterNumber = "FFC 170",
                            VehicleType = "BENSIN"
                        },
                        new
                        {
                            Id = 7,
                            ArrivalTime = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "BMW",
                            CheckoutTime = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "GREEN",
                            Model = "X5",
                            NumberOfWheels = 4,
                            RegisterNumber = "XZS 376",
                            VehicleType = "Desiel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
